name: Build latest (Windows ARM32/64)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-windows-arm
  cancel-in-progress: true

jobs:
#============================================
# ============== ARM32 WINDOWS ==============
# ===========================================
  build-32:
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-armv7
    steps:
      - uses: actions/checkout@v4
      - name: Compile ARM32 Windows builds
        shell: bash
        id: compile
        env: 
          COMMON_FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn"
          WIN32_FLAGS:  "-mwindows -nostartfiles -Wl,-emain_real -DHC_NOMAIN -DHC_GFX_BACKEND=HC_GFX_BACKEND_D3D11"
        run: |
          LATEST_FLAG=-DHC_COMMIT_SHA=\"${GITHUB_SHA::9}\"
          
          cd src
          armv7-w64-mingw32-gcc *.c ${{ env.COMMON_FLAGS }} ${{ env.WIN32_FLAGS }} -o hc-arm32-d3d11.exe $LATEST_FLAG -lwinmm -limagehlp
          
          
      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 32 bit HarmonyClient Windows ARM build <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/hc-arm32-d3d11.exe'
          DEST_NAME: 'HarmonyClient-arm32-Direct3D11.exe'

      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled 32 bit HarmonyClient Windows ARM builds.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

#============================================
# ============== ARM64 WINDOWS ==============
# ===========================================
  build-64:
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Compile ARM64 Windows builds
        shell: bash
        id: compile
        env: 
          COMMON_FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn"
          WIN64_FLAGS:  "-mwindows -nostartfiles -Wl,-emain_real -DHC_NOMAIN -DHC_GFX_BACKEND=HC_GFX_BACKEND_D3D11"
        run: |
          LATEST_FLAG=-DHC_COMMIT_SHA=\"${GITHUB_SHA::9}\"
          
          cd src
          aarch64-w64-mingw32-gcc *.c ${{ env.COMMON_FLAGS }} ${{ env.WIN64_FLAGS }} -o hc-arm64-d3d11.exe $LATEST_FLAG -lwinmm -limagehlp
          
          
      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 64 bit HarmonyClient Windows ARM build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/hc-arm64-d3d11.exe'
          DEST_NAME: 'HarmonyClient-arm64-Direct3D11.exe'

      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled 64 bit HarmonyClient Windows ARM builds.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'